version: '3.8'

services:
  pdf-generator:
    image: reg.hamsaa.ir/pdf-generator:latest
    container_name: pdf-generator
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    environment:
      - CHROME_PATH=/usr/bin/chromium-browser
    volumes:
      - ./output:/app/output  # Optional: Mount a volume to save generated PDFs
    networks:
      - pdf-network
    restart: unless-stopped  # Restart the container unless explicitly stopped

networks:
  pdf-network:
    driver: bridge