version: '3.8'

services:
  pdf-generator:
    image: reg.hamsaa.ir/pdf-generator:latest
    container_name: pdf-generator
    ports:
      - "8080:8080"
    environment:
      - CHROME_PATH=/usr/bin/chromium-browser
    volumes:
      - ./output:/app/output
    networks:
      - pdf-network
    restart: unless-stopped

networks:
  pdf-network:
    driver: bridge